### ISSUE TITLE
SOFT Cache is not working properly when batch inserting

### ISSUE THREAD

**Issue by Toilal** [jankotek/JDBM3#11]
Some records are discarded when saving many values in one commit while soft cache is enabled. There is no problem with cache disabled or MRU cache. In my configuration, transaction are disabled, i don't know if problem occurs when transaction are enabled.

This problem doesn't occur in JDBM2.

**Comment by jankotek** [comment]
Fixed in recent Alpha2. 
Thanks for reporting all this bugs, it really helps.
