### ISSUE TITLE
Error when reading/writing hashmap from two threads

### ISSUE THREAD

**Issue by ajermakovics** [jankotek/JDBM3#17]
In Alpha2 using this code:

``` java
public class DbOp implements Runnable
{
    private static DB db;
    private static String mapName = "map";

    public static void main(String[] args) throws InterruptedException
    {
        db = new DBMaker("db").disableTransactions().disableCache().build();
        if( db.getHashMap(mapName) == null ) db.createHashMap(mapName);

        Thread thread = new Thread(new DbOp());

        thread.start();
        new DbOp().run();

        thread.join();
        db.close();
    }

    public void run()
    {
        Map<Integer, String> map =db.getHashMap(mapName);

        for(int i = 1; i < 10000; i++)
            map.put(i,  map.get(i-1) + i );
    }
}
```

Get an error error: `double get for block 0`

**Comment by Toilal** [comment]
I think it is not supposed to be thread-safe, and you have to synchronyze read/write methods from JDBM collections. (java.util.HashMap is not thread-safe also ...)

**Comment by jankotek** [comment]
Collectios should be thread safe and this is a bug. I am going to fix it soon.

**Comment by Toilal** [comment]
Sorry about that :). Then I hope there will be no impact on performance for single threaded access.

**Comment by jankotek** [comment]
>  no impact on performance for single threaded access.

JDBM3 uses read/write locks, so there is some overhead for single threaded apps. But this overhead is minimal compared to others (diskIO, serialization..). 

My main priority is performance with single thread access, and I am not going to complicate design to gain a few % on multicore tests.

**Comment by ajermakovics** [comment]
I've seen that jdbm2 has a THREAD_SAFE option. Perhaps that could be added to DBMaker

**Comment by jankotek** [comment]
THREAD_SAFE in JDBM2 is fragment from previous versions and is not really used. Overhead of creating and maintaining this option would also be bigger then benefits. As I said overhead of synchronization is very small. 

In future I may start using preprocessor which would remove locks and produce single-thread-optimized jar.

**Comment by ajermakovics** [comment]
Fair enough. What's interesting is that if both threads use the same instance of the map, everything works.

**Comment by jankotek** [comment]
Fixed, problem was caused by two different instances of 'Map', now it uses weak reference to garantee only single instance
