### ISSUE TITLE
I hope that exposed the StorageDiskMapped.sync () method, allows users to call in order to prevent loss of data.

### ISSUE THREAD

**Issue by wjw465150** [jankotek/JDBM3#19]
A suggestion: In disableTransactions environment when use StorageDiskMapped, I hope that exposed the sync () method, allows users to call in order to prevent loss of data.

**Comment by jankotek** [comment]
Hi,
sync method is not exposed. When transactions are enabled, sync is always called. When transactions are disabled, there are many ways how store could get corrupted, and calling sync would not help much. If you want speed, you simply have to close store properly.

**Comment by wjw465150** [comment]
but,When transactions are enabled,I found the commit () method not call MappedByteBuffer.force () method.

**Comment by jankotek** [comment]
Could you be more specific? I just made test and MappedByteBuffer.force() is called. Check StorageDiskMapped.sync() at line 174.

**Comment by wjw465150** [comment]
I mean is: When call the db.commit() but no call StorageDiskMapped.sync()
