### ISSUE TITLE
Creating a mailing group

### ISSUE THREAD

**Issue by menacher** [jankotek/JDBM3#28]
This looks like a promising library. Could you add a mailing group for this tool. Personally, I would like to ask questions on the library than go into the source code each time to find it out.

**Comment by jankotek** [comment]
We have mailgroup since 2009, I will add link to README.md 

Email: jdbm@googlegroups.com
Web: http://groups.google.com/group/jdbm
RSS: http://groups.google.com/group/jdbm/feed/rss_v2_0_msgs.xml

**Comment by menacher** [comment]
Thanks!
