### ISSUE TITLE
hashMap vs treeMap: on add 4 times slower and 3 times bigger on file system. It seems isn't ok?

### ISSUE THREAD

**Issue by terry239** [jankotek/JDBM3#4]
testHcreate 11245 ms. 
testTcreate 2831 ms.

rw-r--r--   1 terry  LD\domain users    62M  3 фев 12:20 test.hash.dbm.d.0
-rw-r--r--   1 terry  LD\domain users   654K  3 фев 12:20 test.hash.dbm.i.0
-rw-r--r--   1 terry  LD\domain users     2B  3 фев 12:20 test.hash.dbm.t
-rw-r--r--   1 terry  LD\domain users    20M  3 фев 12:20 test.tree.dbm.d.0
-rw-r--r--   1 terry  LD\domain users   166K  3 фев 12:20 test.tree.dbm.i.0
-rw-r--r--   1 terry  LD\domain users     2B  3 фев 12:20 test.tree.dbm.t

int size = 300000;
    int commitSize = 50000;
    DB build = new DBMaker("test.hash.dbm").setMRUCacheSize(100).build();
    Map<String, String> hashMap = build.createHashMap("hashMap");
    final Stopwatch start = Stopwatch.start();
    for (int i = 0; i < size; i++) {
      hashMap.put(i + "asdddfdgf" + i + "sddfdfsf" + i, "dsfgfg.dfcdfsgfg" + i);
      if (i % commitSize == 0) {
        build.commit();
      }
    }
    build.commit();
    build.close();
    System.out.println("testHcreate " + start.newLoop() + " ms. ");

```
build = new DBMaker("test.tree.dbm").setMRUCacheSize(100).build();
Map<String, String> treeMap = build.createTreeMap("treeMap");
for (int i = 0; i < size; i++) {
  treeMap.put(i + "asdddfdgf" + i + "sddfdfsf" + i, "dsfgfg.dfcdfsgfg" + i);
  if (i % commitSize == 0) {
    build.commit();
  }
}
build.commit();
build.close();
System.out.println("testTcreate " + start.newLoop() + " ms. " );
```

**Comment by terry239** [comment]
Ok. It seems, common implementation issues. Dbm2 have same space occupation and perfomance.

On my data TreeMap a bit better on write in dbm3. But read in dbm2 still faster on 20-30%

**Comment by jankotek** [comment]
Hi,
in short TreeMap has more advanced implementation in JDBM. For example it uses delta key compression which could explain smaller size.

Secondly I changed lot of parameters (page size, node size) and I did not do 'calibration' yet. So hash tree may be slower bcos its sizes are wrongly set.

**Comment by jankotek** [comment]
BTree is much faster with linear inserts. HTree is faster with random access. So work as designed.
