### ISSUE TITLE
Collection binding as simpler Secondary Collections

### ISSUE THREAD

**Issue by jankotek** [jankotek/JDBM3#43]
JDBM2 had Secondary Collections, it was view with existing collection with an alternative date. This made API bloated and complicated. 

We should introduce collection binding (as set of static method). It should take two existing collections, attach listener on first, and modify second accordingly. This should be significantly simpler than Secondary Collection while having 80% functionality. User will also have better control over its data.

**Comment by jankotek** [comment]
JDBM4...

**Comment by DerArvid** [comment]
Hello Jan,

can you show me a sample code with this Collection binding?

Thanks and greetings
Arvid

**Comment by jankotek** [comment]
JDBM3 does not have it. I redirected my afford to JDBM4 which does not have it yet either.
