### ISSUE TITLE
Checking for the existence of a named collection

### ISSUE THREAD

**Issue by holopoj** [jankotek/JDBM3#5]
Is there a proper method of checking whether a named collection already exists in a database?  I tried calling DB.getHashMap("name_that_doesnt_exist") thinking it might return null if I haven't previously called DB.createHashMap("name_that_doesnt_exist").  Instead, the database throws an IllegalArgumentException.  Is/Will there be a way to check this other than catching the exception?

Sorry if this isn't really an "issue", I couldn't find a mailing list so I posted here.

**Comment by jankotek** [comment]
No there is not, I will add it soon.

Jan

**Comment by jankotek** [comment]
Fixed, getXXX now returns null if collection was not found.
