### ISSUE TITLE
Delete or List structure from DB ?

### ISSUE THREAD

**Issue by Toilal** [jankotek/JDBM3#6]
We need to delete a structure (HashMap, TreeMap, or another ...) from a JDBM Database. We also need to retrieve a list name of all existing structures in the JDBM Database.

Is it possible to perform this with actual API ?

**Comment by jankotek** [comment]
No, it is  not possible. I will add this soon.

Jan

**Comment by jankotek** [comment]
added functions 'DB.listCollections()' and 'DB.deleteCollection(name)'
