### ISSUE TITLE
A suggestion: can like "LevevDB" way, so that the database is composed of many small files, reducing the risk of loss.

### ISSUE THREAD

**Issue by wjw465150** [jankotek/JDBM3#62]
A suggestion: can like "LevevDB" way, so that the database is composed of many small files, reducing the risk of loss.

**Comment by jankotek** [comment]
Not a chance. Heaving large amount of files slows down write operations, as calling sync() on large number of files is slow. Also JDBM have very little redundancies, so risk of corruption of entire store is high, even with small data loss.

You may implement this on your own by extending 'Store'. It should be soon part of public API.
But I will not integrate such patch.
