### ISSUE TITLE
cant Serializable google object HashBasedTable

### ISSUE THREAD

**Issue by xdylxdyl** [jankotek/JDBM3#63]
Test Code:

Table<String,String,String> table=HashBasedTable.create();
         table.put("xx", "yy", "11");
         table.put("xx", "yy2", "11");
         table.put("xx", "yy2", "22");
         Map<String, String> ss=table.column("yy2");
         log.info(ss);
         Map<String,String> keys=table.row("xx");
         log.info(keys);
         log.info(table.column("yy"));
         log.info(table);

```
    DBMaker maker=new DBMaker("db/contact");
    DB db=maker.build();
    //db.createHashMap("tableMap");
    //db.commit();

    Map<String,Table> map = db.getHashMap("tableMap");

    log.info(map.size());

    //map.put("table", table);
//  db.commit();

    Table t2 = (Table) db.getHashMap("tableMap").get("table");


     log.info(t2.column("yy"));
```

 cant work

**Comment by xdylxdyl** [comment]
```
    and this is pom of guava
```

<dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>11.0.1</version>
        </dependency>

**Comment by jankotek** [comment]
Looks like issue with serialization, fill fix it in couple of weeks

**Comment by jankotek** [comment]
Problem is not in JDBM. One class in Guava does not implement Serializable
   java.io.NotSerializableException: com.google.common.collect.StandardTable$Column
