### ISSUE TITLE
Support serialization of enums

### ISSUE THREAD

**Issue by romix** [jankotek/JDBM3#71]
I have the following enum declared in my tests:

enum Order
    {
        ASCENDING,
        DESCENDING
    }

But values of this enumeration are not serialized properly.  E.g. if I try to serialize Order.ASCENDING, JDBM3 claims that it is serialized, but when I read it back, the value is not the same, it is empty.

Looks like SerialClassInfo.writeObject cannot find any fields in this class and therefore does not write any values for it.

May be enumerations need special handling? 

Also keep in mind that enumerations may optionally have fields and methods, e.g. as described here:
http://docs.oracle.com/javase/1.5.0/docs/guide/language/enums.html

**Comment by romix** [comment]
I think I fixed it and also fixed a few more places related to serialization (handling of arrays, support for IdentityHashMap objects, etc). 

I also compared it to Java serialization, Kryo, protostuff-runtime. The results have shown that serialization is very compact in terms of produced size (it beats both Kryo and ptotostuff on my tests), but it is very slow (ten times slower than others). Quick profiling has shown that SerialClassInfo methods createInstance, getFieldValue and setFieldValue are very slow, because they use a lot of reflection and they often do the same work for the same class many times. I added some caching of class-specific information. Now serialization is about 10-20 times faster! It is now faster then Java serialization, but still slower then Kryo and protostuff. At the same time, it still produces very nice and compact serialized representation.

Here are the numbers I get now:

Size of serialized representation using JavaSerializer: 3438
Speed of JavaSerializer: 10000 iterations in 6490 ms; 1.5408320493066257 iterations/ms

Size of serialized representation using JDBMSerializer: 499
Speed of JDBMSerializer: 10000 iterations in 5834 ms; 1.7140898183064792 iterations/ms

Size of serialized representation using KryoSerializer: 1510
Speed of KryoSerializer: 10000 iterations in 4103 ms; 2.4372410431391667 iterations/ms

Size of serialized representation using KryoCompressedSerializer: 213
Speed of KryoCompressedSerializer: 10000 iterations in 4244 ms; 2.35626767200754 iterations/ms

Size of serialized representation using protostuff-default-id-strategy: 2597
Speed of protostuff-default-id-strategy: 10000 iterations in 3276 ms; 3.0525030525030523 iterations/ms

Size of serialized representation using protostuff-strict-num-id-strategy: 679
Speed of protostuff-strict-num-id-strategy: 10000 iterations in 1825 ms; 5.47945205479452 iterations/ms

Size of serialized representation using protostuff-auto-num-id-strategy: 677
Speed of protostuff-auto-num-id-strategy: 10000 iterations in 2123 ms; 4.710315591144607 iterations/ms

Size of serialized representation using GZIP-protostuff-auto-num-id-strategy: 405
Speed of GZIP-protostuff-auto-num-id-strategy: 10000 iterations in 3198 ms; 3.1269543464665417 iterations/ms

Please let me know how I should contribute the code? Should I fork your project, change files and add pull request? Or should I just put the 3 changed files on a gist and you can copy them from there?

**Comment by romix** [comment]
I optimized it even further. It now produces the smallest non-compressed and second-smallest compressed serialized representations and it is now faster than Java serialization, Kryo and protostuff. And the last two are known for their speed!

New numbers:
Size of serialized representation using JavaSerializer: 3438
Speed of JavaSerializer: 100000 iterations in 60731 ms; 1.6466055227149232 iterations/ms
Size of serialized representation using JDBMSerializer: 499
Speed of JDBMSerializer: 100000 iterations in 11544 ms; 8.662508662508662 iterations/ms
Size of serialized representation using GZIP-JDBMSerializer: 271
Speed of GZIP-JDBMSerializer: 100000 iterations in 24508 ms; 4.080300310102824 iterations/ms
Size of serialized representation using KryoSerializer: 1510
Speed of KryoSerializer: 100000 iterations in 28969 ms; 3.451965894576962 iterations/ms
Size of serialized representation using KryoCompressedSerializer: 212
Speed of KryoCompressedSerializer: 100000 iterations in 49436 ms; 2.0228173800469293 iterations/ms
Size of serialized representation using protostuff-default-id-strategy: 2597
Speed of protostuff-default-id-strategy: 100000 iterations in 22729 ms; 4.399665625412469 iterations/ms
Size of serialized representation using protostuff-strict-num-id-strategy: 679
Speed of protostuff-strict-num-id-strategy: 100000 iterations in 21575 ms; 4.634994206257242 iterations/ms
Size of serialized representation using protostuff-auto-num-id-strategy: 677
Speed of protostuff-auto-num-id-strategy: 100000 iterations in 17222 ms; 5.8065265358262685 iterations/ms
Size of serialized representation using GZIP-protostuff-auto-num-id-strategy: 407
Speed of GZIP-protostuff-auto-num-id-strategy: 100000 iterations in 34726 ms; 2.8796866900881186 iterations/ms

 An even faster implementation is available as well, but it would need to use the ASM byte-manipulation framework and reflectasm library  (http://code.google.com/p/reflectasm/). And I'm not sure you want to add new dependencies to the JDBM project due to the binary JARs size consideration. Please let me know, if the dependency on reflectasm is OK, and I can provide this even faster implementation.

**Comment by jankotek** [comment]
Thanks for you commit, it is nice and solid work.

The truth is that I did not concentrate on POJO serialization speed much yet. My priority was serialized data size. Current implementation was as simple as possible. I was planning to improve POJO serialization speed in JDBM 3.1 and this commit saves me lot of work. 

I know Kryo and bytecode manipulation speedup it uses. There is chance I will adopt it into JDBM (can be done even without dependecy). But it is not my priority right now.

**Comment by romix** [comment]
I'm glad you included my pull request into trunk.

> I know Kryo and bytecode manipulation speedup it uses. There is chance I will adopt it into JDBM (can be done even 
> without dependecy). But it is not my priority right now.

On my serialization-heavy tests, current JDBM3 serialization with my patches is only slightly slower than the same patch but with bytecode manipulation. In both cases it is way faster than Kryo (almost 2 times faster). So, you don't need to use Kryo, unless you want some other features of it besides the raw speed.

Regarding the version using bytecode manipulation, please have a look at the small lib called Quickser (https://github.com/romix/quickser) which I created out of JDBM3 serialization. This library contains some further improvements compared to the accepted pull request and uses bytecode manipulation when it is possible.

I'd be interested to hear if those accepted serialization changes improve JDBM3 overall performance in any way. I couldn't test it, because I only had some tests for pure serialization speed. But I guess you know best, which use-cases were slow before due to serialization. It would be interesting to test them now with those changes.
