### ISSUE TITLE
Inherited fields are not serialized.

### ISSUE THREAD

**Issue by Toilal** [jankotek/JDBM3#8]
@see http://pastebin.com/RuXFsxD1 (Base class TestBean2.java)
@see http://pastebin.com/Yb2Hd1Zu (Derived class DerivedBean.java)
@see http://pastebin.com/EKuHNiTi (Unit test)

Unit test doesn't pass, because fields from TestBean2 base class are null. JDBM File doesn't contains inherited field definitions.

**Comment by Toilal** [comment]
I have fixed this issue.

```
    ObjectStreamClass streamClass = ObjectStreamClass.lookup(clazz);
    ObjectStreamField[] fields = streamClass.getFields()
```

This lookup grab information for clazz, but fields doesn't contains fields from superclass. Here is a code to use instead.

```
private ObjectStreamField[] getFields(Class clazz) {
    ObjectStreamClass streamClass = ObjectStreamClass.lookup(clazz);
    FastArrayList<ObjectStreamField> fieldsList = new FastArrayList<ObjectStreamField>();
    while (streamClass != null) {
        for (ObjectStreamField f : streamClass.getFields()) {
            fieldsList.add(f);
        }
        clazz = clazz.getSuperclass();
        streamClass = ObjectStreamClass.lookup(clazz);
    }
    ObjectStreamField[] fields = new ObjectStreamField[fieldsList.size()];
    for (int i = 0; i < fields.length; i++) {
        fields[i] = fieldsList.get(i);
    }
    return fields;
}
```

This method should be called by SerialClassInfo class, in registerClass(Class) and writeObject(DataOutput, Object, FastArrayList) methods.

Then the unit test pass properly.

**Comment by jankotek** [comment]
I used your fix, thanks
