### ISSUE TITLE
Cannot handle multiple threads

### ISSUE THREAD

**Issue by Hardcore-fs** [jankotek/JDBM3#81]
Even something like adding/removing multiple records cannot be threaded.

**Comment by jankotek** [comment]
Could you be more specific?
JDBM3 should be thread safe.

Jan

**Comment by Hardcore-fs** [comment]
I was using it to store url's from a high-speed crawler, fed by 50 threads
I kept getting concurrency warnings from the JVM.
I'm now using  "ehcache" and the problems have dissapeared

**Comment by jankotek** [comment]
It sounds like you got ConcurrentModificationException, which is by design. JDBM3 has fail-fast iterators. Something which should improve in JDBM4
