### ISSUE TITLE
DBMaker.closeOnExit option causes memory 'leak'

### ISSUE THREAD

**Issue by hamishmorgan** [jankotek/JDBM3#82]
The option to automatically close a database on JVM exit (`DBMaker.closeOnExit()`) leaks a reference to the DB object, causing it to never be GC'd, even when a manual close has been performed. Here's the relevant snippet from DBMaker:

``` java
        if(closeOnJVMExit){
            final DB db2 = db;
            Thread t = new Thread("JDBM shutdown"){
              public void run(){
                  if(!db2.isClosed())
                    db2.close();
              }
            };
            Runtime.getRuntime().addShutdownHook(t);
        }
```

To resolve this the shutdown hook probably needs to be removed on `DB.close()`.

**Comment by jankotek** [comment]
Fixed
