### ISSUE TITLE
JDBM3 files taking lot of time to load Data files.

### ISSUE THREAD

**Issue by babaprakash** [jankotek/JDBM3#83]
Hi, 
As part of development we are using JDBM3 cache for storing data. We have configured JDBM3 using Spring dependency injection. Here is our spring configuration file.

File file = new File(path);
        if (!file.exists() && !file.mkdirs()) {
            throw exception ;
        }
        db = DBMaker.openFile(path + fileName).useRandomAccessFile()
                                              .disableTransactions()
                                              .enableMRUCache()
                                              .closeOnExit()
                                              .make();

bean id="jdbm" factory-bean="jdbmFactory" factory-method="create" scope="singleton"

bean id="jdbmFactory" class="com.jdbm.Jdbm3Factory" destroy-method="close"
        constructor-arg index="0" value="jdbm3"
        constructor-arg index="1" value="/tmp/cores_data/"
        property name="name" value="user"
bean

as per above configuration Once we populate data using JDBM3 api it is creating file with names jdbm3.d.0 and jdbm3.i.0. These data files are of size around 500 MB. when we try to start the server, JDBM3 is trying to get these large data files into memory..because of that it is taking lot of time to start the server. When i checked catalina.out file i am seeing lot of  
Garbage collection error messages..
Unloading class sun.reflect.GeneratedSerializationConstructorAccessor34

I have tried increasing heap space..but still it did not help me...And we are not facing this problem with small amount of data..we are getting this problem only when we insert large amount of data.

Can you please help us to resolve this problem.

**Comment by wjw465150** [comment]
enableMRUCache() change to : enableSoftCache()

**Comment by jankotek** [comment]
I tried test case bellow with 32MB heap,  without success. I will need more informations, preferably test case to reproduce this issue

```
    String f = newTestFile();
    DB db = DBMaker.openFile(f)
            //.useRandomAccessFile()
            .disableTransactions()
            .enableMRUCache()
            .make();

    Map m = db.createTreeMap("test");
    for(int i = 0;i<1e7;i++){
        m.put(i,"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
    }

    db.close();

    //this should fail with limited memory
    db = DBMaker.openFile(f)
            .useRandomAccessFile()
            .disableTransactions()
            .enableMRUCache()
            .make();

    m = db.getTreeMap("test");
```

**Comment by babaprakash** [comment]
Hi,
Thanks for your reply.

Please find details below. Here is our code details.

path = <data files location>

File file = new File(path);
        if (!file.exists() && !file.mkdirs()) {
            throw exception;
        }
        db = DBMaker.openFile(path + fileName).useRandomAccessFile().enableMRUCache().make();
Here CacheableData is a java Object.

Map<Long, CacheableData> map = db.getHashMap("test");
if (map == null) {
            map = db.createHashMap(test);
}
map.put(key, CacheableData);
factory.commit();
After we commit the data, JDBM3 is storing complete data in path location. And i have mentioned my spring configuration in my earlier comment.

Here is the test Case:

CacheableData data = new CacheableData(1L);
        data.setEmpCode("10410271");
        data.setFirstName("Babaprakash");
        data.setLastName("Dabbara");
        for(Long i = 0L; i < 10000000; i++) {
map.put(i,data );
}
CacheableData data_re = map.get(100L);
assertNotNull(data_re );

Please let me know if you require some more details.

**Comment by jankotek** [comment]
Not going to fix, please reopen in JDBM4 if it persist
