### ISSUE TITLE
createTreeMap() does not allow to load existing data

### ISSUE THREAD

**Issue by tbocek** [jankotek/JDBM3#86]
The following testcase fails:

@Test
public void loadDB()
{
    String dirName = "/tmp/jdbm";
    DB db = DBMaker.openFile(dirName).disableTransactions().make();
    Map<String, String> dataMap = db.<String, String>createTreeMap("test-map");
    dataMap.put("hallo", "test");
    db.close();
    db = DBMaker.openFile(dirName).disableTransactions().make();
    dataMap = db.<String, String>createTreeMap("test-map"); 
}

java.lang.IllegalArgumentException: Object with name 'test-map' already exists
    at org.apache.jdbm.DBAbstract.assertNameNotExist(DBAbstract.java:349)
    at org.apache.jdbm.DBAbstract.createTreeMap(DBAbstract.java:243)
    at org.apache.jdbm.DBAbstract.createTreeMap(DBAbstract.java:234)
    at org.apache.jdbm.DBAbstract.createTreeMap(DBAbstract.java:31)
    ...

The JavaDoc says "Creates or load existing Primary TreeMap which persists data into DB.", however, I can create but not load.

**Comment by jankotek** [comment]
Javadoc is wrong, use DB.get().

**Comment by jankotek** [comment]
Javadoc fixed
