### ISSUE TITLE
Plan for an native index support

### ISSUE THREAD

**Issue by aniljava** [jankotek/JDBM3#9]
Is there any KEY-SET and KEY-LIST implementation in plan ?

**Comment by jankotek** [comment]
I guess you mean multimap implementation as described here:
http://commons.apache.org/collections/api-3.1/org/apache/commons/collections/MultiMap.html

We do not plan special support for this. However ArrayList has very good support in JDBM3, so using Map<String,ArrayList<String>> should be efficient for most cases.

**Comment by jankotek** [comment]
I meant Map[String,ArrayList[String]]
