### ISSUE TITLE
Support serializing/deserializing Hadoop keys and values

### ISSUE THREAD

**Issue by ghost** [jankotek/JDBM3#91]
It shouldn't be a problem, just a simple extension as Hadoop keys and values implements the Writable interface, which specifies a write and a read. These methods uses the DataOutput and DataInput, as is done in the JDBM3 Serialization class. So it is just a simple matter of extending the Serialization class and Hadoop keys and values will be serializable and fast. 

At least as I see it :-)

**Comment by jankotek** [comment]
Just write custom Serializer for your class and supply it with map creation
